# Generated by Django 5.2.9 on 2025-12-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_id",
                    models.CharField(
                        help_text="Identifier grouping notes belonging to the same chart",
                        max_length=100,
                    ),
                ),
                (
                    "note_id",
                    models.CharField(
                        help_text="Unique identifier for the note from the source document",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        help_text="Type/category of the note (e.g., HPI, ROS, ALLERGIES)",
                        max_length=100,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Free-text clinical content of the note"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the note was created",
                    ),
                ),
            ],
        ),
    ]
